# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 600668cc5cd6f2fff8ed08f222ab3e6d6c31f851120797e89022773a667a46f85d17b3f9be1ab0eda586ded14618da277f3a400326bbb03e347c70ef744aa763

test:
  secret_key_base: 517cf7dcc7c6e42c258a1fdb933dfc0df283784b6cdae379f01a6a6cc0a1658e60da67b2b75f78cf69b46b32f6cf386faba3e2f1262f494c9f5e53158ab318d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
